### ISSUE TITLE
Issues related to training the model for continuous variables

### ISSUE THREAD

**Issue by Katsk1** [btheodorou99/HALO_Inpatient#10]
Hi,

Thank you for providing the source code of the HALO. 

I've been trying to implement the version that allows the continuous variables. However, I noticed that the genDatasetContinuous.py does not actually include gender or ethnicity in the data altough the model configuration has vocab size configured to these variables. The resulting data includes only diagnosis codes, then procedure codes (if any), medications (if any) and age and then the variables provided in the episode{}_timeseries.csv (if available). The gender is processed by saving it on line 62 to `patientRow` but this is not included in the data later and there is no mention about the ethnicity at all. Am I missing something or is the code incompelete? 

Regarding the episode{}_timeseries.csv, are you aware that some patients actually do have that data but because the data cleaning program provided by another author excludes patients with transitions, and it seems that all patients that had more than one admission also had transitions, this data is excluded? Therefore your training data is not complete in that sense that this information is absent although the patients have it. In other words, the lab data is empty for these patients even though it exists in original MIMIC-III data but because using someone else's code to preprocess the data, this information is now missing.

Also I'm running into issues in line 63 when training the model. `batch_ehr[i,j+2][v]` gives IndexError: index 150 is out of bounds for axis 1 with size 150. I had the similar issue with the bare-bones version (just the diagnosis codes) and was able to resolve it by increasing the total_vocab_size=7000 instead of 6869. I have no experience of language models, so no idea if that was a good idea or not to increase it but at least I was able to train the model. Based on the value in that error and the config.py for continuous variable model, I assume this error is somehow related to `n_positions=150` or `n_ctx=150` but since I do not understand what these parameters are, I hope you could help me with this error.

If you'd like to have video call with me, please email me kakype [at] utu.fi.

**Comment by btheodorou99** [comment]
Hello, thank you for your comments. For the first part, yes the dataset does not include gender or ethnicity codes as labels. I can not remember if those variables in the config were meant as an example of things that could be added or just artifacts from past experiments, but they do not correspond to the experiments in the paper/contents of the dataset generation script. They could be included as labels (as you mentioned a gender variable is already captured but not used) but are not used in the current set up, and I have removed them from the config.py file for now.

For the second part, I was aware that the number of patients dropped but not aware of all the specific issues with the processing of that baseline dataset script. We wanted to make the more computationally challenging lab processing easier by using that external script, and we also wanted stay aligned with the benchmark dataset for the purposes of other validation/experiments as well. However, an improved dataset could certainly be built by augmenting the dataset building script and building your own lab time series values.

Finally for the third part, the config file vocab sizes are meant to be changed once you build the dataset based on the specifics of your constructed dataset. So, 6869 would need to be changed (based on the CODE_VOCAB_SIZE and LABEL_VOCAB_SIZE print statements at the end of the dataset generation script), and then the 150 does correspond to n_positions/n_ctx (they mean different things in the context of the architecture but should be kept the same for the basic setup) which is the maximum number of time steps. I will add a commit within the dataset generation script to cut things off that go beyond this time step. It is a challenge/problem that we end up cutting off records with many visits because the lab time series make them go past this limit - there are some ways around this but it fell outside the scope of this paper/repository.

**Comment by Katsk1** [comment]
Hi, thanks for a prompt reply and clarification. Just in case I want to add gender and ethnicity later (or any static vairable for that matter), do I just append them to the label list or should I include separate lists called gender and ethnicity into the data?

**Comment by btheodorou99** [comment]
Yes, you would append (or replace if you wanted to remove something else) to the same label list. The structure of the data should be the same with a single "labels" key in the patient dictionary which maps to a label vector, but the contents/meaning of that vector can be adjusted however you want. Just make sure to change the config vocab sizes if the number of label variables changes.

**Comment by Katsk1** [comment]
Hello, I apologize for reaching out again, but I'm encountering difficulties in grasping the decoding process. In [genDatasetContinuous.py line 191](https://github.com/btheodorou99/HALO_Inpatient/blob/53e643d5128244507ab15557527501f5851d4a09/continuous_variables/genDatasetContinuous.py#L191), you map the vocabulary to indices encompassing diagnoses, procedures, and prescriptions. My understanding is that post data generation, the resulting synthetic dataset remains in this encoded form. Is my assumption correct? If so, I gather that decoding the synthetic data using this vocabulary should be relatively straightforward. However, the challenge lies in the fact that the vocabulary is shared among all these variables. Consequently, some diagnoses codes might be misinterpreted as prescriptions or procedures, and vice versa. Essentially, the synthetic data may contain nonsensical entries. My objective here is to develop a solution that reverts the synthetic data generated by HALO to a format resembling its original state, i.e., separate, clean, human-readable CSV files, as they align better with my objectives.
