### ISSUE TITLE
Age as first time since last visit in pickleToCSV.py

### ISSUE THREAD

**Issue by Katsk1** [btheodorou99/HALO_Inpatient#18]
Hi, thanks for creating this code. It helped explain why there are unusual diagnosis codes in the code list. I initially assumed that the first element contained ICD codes, the second procedures, the third NDC codes, and the fourth was age. I was surprised that the second and third elements were almost always empty, but it seems all codes are included in the first list.

However, after running the code and comparing the results to my own CSV transformation code, I noticed an issue: the age (fourth element) is copied to the first observation of the time since the last visit. This means that the time since the last visit for visit number 1 is not accurate; it’s actually the patient’s age. Could you fix this so that the age is in a separate column and repeated over the rows, similar to the binary label variables? Alternatively, please clarify this in the code documentation so users can adjust their post-cleaning process accordingly and avoid confusion about the nonsensical first time since the last visit value.

**Comment by btheodorou99** [comment]
Thanks for catching this! I've adjusted the code and a clarification in the documentation around that section

**Comment by Katsk1** [comment]
Thanks for the quick response and action. This question isn't directly related to the current issue but concerns the format of the data used in the source code. Could you clarify why all the codes are in the first list, while the second and third lists are empty, and age is correctly included in the fourth? I noticed that in row 130 of genDatasetContinuous.py, this list of four elements is created, but I don't understand why medications and procedures are empty while age is correctly placed in the fourth position. Am I missing something here? Additionally, in my synthetic data, 64 subjects had one observation in those lists, even though they are all empty in my training data. I assume this is due to the randomness of the method, but could you confirm this?

**Comment by btheodorou99** [comment]
Hello, most of the formatting things you've identified are just data design decisions. There's a good chance they're not optimal as I was still playing around with multiple things while running these experiments. The first list includes all medical codes while the second and third lists are lab tests (broken down into presences and values between the two lists). The medications/procedures in the genDatasetContinuous file are just temporarily separate, they are combined into the first data list in the data representation. The reason the second and third lists are empty in the first visit is because we represent the ICU stay as a static visit (medical codes, time gap with the first time gap being from birth) and then a series of lab time series visits which don't have medical codes (so empty first list) but have labs (things in the second and third visit). However, yes the randomness of the method would likely cause things to pop up that we wouldn't expect, especially depending on how long the model is trained for. Again, a lot of this data representation is arbitrary and I think a better way now to do it would be separate models for static visits and then lab time series conditioned off them, but this is how it was done for these experiments.

**Comment by Katsk1** [comment]
Thank you for your reply and for your cooperation. It's great to see that you're active and helping others understand and use your method.
