### ISSUE TITLE
questions about continuous data generation

### ISSUE THREAD

**Issue by BreezeHavana** [btheodorou99/HALO_Inpatient#5]
Hi, I have read your impressive paper about ehr data generation. I tried to generate continuous data using this code, both github issues and paper mentioned that HALO can generate continuous data like lab values. I also noticed there is a variable "tsDf" in "genDatasetContinuous.py" reading timeseries data and I assumed "tdDf" contains lab values. But there is no csv files in MIMIC with format like "episode{visit_count}_timeseries.csv", so I am wondering how to process lab values dataset. I would be appreciated if you are so kind to provide the script of processing labevents and d_labitems in MIMIC, or the detailed format of "episode{visit_count}_timeseries.csv". Thanks!

**Comment by btheodorou99** [comment]
Hello, my apologies for the limited documentation regarding the usage of the continuous data generation module. I've had a number of questions about that code, and we have found a number of errors stemming from subsequent changes since the experiments. I have also realized that given the interest, this section requires its own specific README guide, and I have added one to that directory. However, the answer to your specific question is that the time series .csv's come from preprocessing performed in the https://github.com/YerevaNN/mimic3-benchmarks benchmark repository (this is also the source of phenotype mappings used in the main experiments). That repository has good documentation, but you just need to get through the extract_episodes_from_subjects and then point the timeseries_dir variable to the correct spot. Hope this helps, and please let me know if you have any further questions.

**Comment by BreezeHavana** [comment]
auto reply
