### ISSUE TITLE
Can HALO fill missing values?

### ISSUE THREAD

**Issue by BreezeHavana** [btheodorou99/HALO_Inpatient#8]
Thanks for the detailed response before, I have generated synthetic data using custom dataset. But there is still one thing to consider, there are quite a few missing values, can HALO help me to fill them? I would be appreciated if given some prompt. Thanks!

**Comment by btheodorou99** [comment]
Hello, are the missing values in the dataset where you are looking to repair them with HALO or are you generating with HALO and expecting values (e.g. one of a group of values) but not getting them? The first is not necessarily the core design but could be achieved by for example assigning missing values a code and then either masking that code's probability or only keeping patients without that code. HALO could also extend or fill in if the missingness is entire time steps. If it is the latter, that is a separate task that isn't included in this model code, but as a simple fix you could either only keep non-missing patients (and generate extra, depending on how prevalent the missingness is) or add some logic within the generation loop in model.py to make sure that one of an expected group of values is present and either randomly pick one of the values if they are missing (or more properly pick the last one since it is autoregressive and the last one would come by default if the first are all missing). There are multiple ways and spots to do this depending on your specific setting.

**Comment by BreezeHavana** [comment]
auto reply

**Comment by BreezeHavana** [comment]
Hi, it is the first situation, there are ehr series containing nans and I would like to fill them. Thanks for your suggestion about masking. There is still a question that,  in data generation, how to solve the confliction of adjacent intervals? For example, if there are 3 intervals like[0, 10], [10, 20] and [20, 30] and visits is in the form of [0, 0, 0], what if the model give a prediction like [0, 1, 1], as the value can not be both in the interval [10, 20] and [20, 30]?

**Comment by btheodorou** [comment]
You could add some logic within the model.py file (either directly or by configuring it to take in some rules) such that once one is set to 1, none of the subsequent intervals can be set to 1 (and if you're expecting exactly 1, if none of the first ones are set, the last one is).

**Comment by BreezeHavana** [comment]
Thanks, I tried to find relevant codes for solving adjacent confliction in HALO but didn't find any...Thanks for your detailed explanation!

**Comment by btheodorou99** [comment]
It has a more temporal and clinical rule rather than "one of a category" focus, but we did also just have a follow-up work looking at ensuring logically coherent generations with HALO. The code for that can be found at https://github.com/btheodorou/KnowledgeInfusion if that helps at all.
